---
- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_private_key_path }}/{{ cert_ca_common_name }}.key"
    type: "{{ cert_ca_type }}"
    size: "{{ cert_ca_size }}"
    owner: "{{ cert_owner }}"
    group: "{{ cert_group }}"
    mode: "0600"

- name: Create a CSR for the CA certificate.
  community.crypto.openssl_csr:
    path: "{{ cert_csr_path }}/{{ cert_ca_common_name }}.csr"
    privatekey_path: "{{ cert_private_key_path }}/{{ cert_ca_common_name }}.key"
    country_name: "{{ cert_ca_country_name }}"
    organization_name: "{{ cert_ca_organization_name }}"
    email_address: "{{ cert_ca_mail_address }}"
    common_name: "{{ cert_ca_common_name }}"
    owner: "{{ cert_owner }}"
    group: "{{ cert_group }}"
    subject_alt_name: "{{ cert_ca_san }}"
    basic_constraints: "{{ cert_ca_basic_constraint }}"
    mode: "0644"

- name: Create the CA certificate
  community.crypto.openssl_certificate:
    path: "{{ cert_ca_path }}/{{ cert_ca_common_name }}.pem"
    privatekey_path: "{{ cert_private_key_path }}/{{ cert_ca_common_name }}.key"
    csr_path: "{{ cert_csr_path }}/{{ cert_ca_common_name }}.csr"
    owner: "{{ cert_owner }}"
    group: "{{ cert_group }}"
    provider: "{{ cert_ca_provider }}"
    mode: "0644"
